[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "map-plane"
version = "0.1.0"
description = "Visualisation of electron density planes in ultra-high resolution protein crystal structures."
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Rachel Alcraft", email = "Rachel.Alcraft@gmail.com" },
]
dependencies = [
    "biopython==1.81",
    "pandas",
    "numpy",
    "scipy",
    "matplotlib",
    "plotly",
    "kaleido==0.2.1", # v1.0+ requires Chrome — pinned to avoid this dependency
]

[project.optional-dependencies]
test = ["pytest", "ruff"]
dev = ["pytest", "ruff", "ipykernel", "jupyter", "pre-commit", "scikit-learn", "streamlit", "umap-learn", "hdbscan", "biopython==1.81", "pydssp", "rcsb-api"]
ml = ["torch", "torchvision", "rcsb-api", "Pillow", "scikit-learn", "streamlit", "timm==0.9.16", "huggingface_hub"]
analysis = ["scikit-learn", "streamlit", "umap-learn", "hdbscan", "biopython==1.81", "pydssp", "rcsb-api"]

[tool.hatchling.build.targets.wheel]
packages = ["src/map_plane"]